FROM ubuntu:22.10

ARG DEBIAN_FRONTEND=noninteractive

RUN apt update -y && apt upgrade -y
RUN apt -y install software-properties-common

RUN apt -y install apache2 libapache2-mod-fcgid && \
a2enmod rewrite actions fcgid alias proxy_fcgi
RUN echo "ServerName localhost" >> /etc/apache2/apache2.conf
COPY src/000-default.conf /etc/apache2/sites-available/000-default.conf

RUN apt-get update && apt install -y php8.1

RUN rm /var/www/html/index.html
COPY src/info.php /var/www/html/info.php

RUN apt-get install -y supervisor
ADD src/supervisord.conf /etc/supervisor/conf.d/supervisord.conf 

EXPOSE 80

ENTRYPOINT ["/usr/bin/supervisord"]
